enhance: make outlook mail tools self-contained
gptscript-ai/tools pull request #85
Opened 2024-10-09 19:59 UTC by njhale

- **enhance: make outlook mail tools self-contained**
- **enhance: add outlook mail tool bundle**

2024-10-09 20:02 UTC, g-linville requested changes

2024-10-09 20:02 UTC, g-linville commented on outlook/mail/tool.gpt
> +Share Tools: List Mail Folders, List Messages, Search Messages, Create Draft, Send Draft, Delete Message, Move Message
`Get Message Details` is missing here.

2024-10-10 14:06 UTC, njhale commented on outlook/mail/tool.gpt
> +Share Tools: List Mail Folders, List Messages, Search Messages, Create Draft, Send Draft, Delete Message, Move Message
fixed

2024-10-10 15:06 UTC, g-linville approved these changes

2024-10-10 15:26 UTC, merged